name: new_base_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  dio: ^5.4.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_bloc: ^8.1.4
#  flutter_local_notifications: ^17.2.1
  freezed_annotation: 2.4.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^7.6.7
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  package_info_plus: ^8.3.0
  intl: ^0.20.1
  path_provider: ^2.1.5
  google_maps_flutter: ^2.10.1
  intl_translation: ^0.20.1
  currency_text_input_formatter: ^2.1.13
  url_launcher: ^6.2.5
  pretty_dio_logger: ^1.4.0
  introduction_screen: ^3.1.14
  image: ^4.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_flavorizr: ^2.2.3
  freezed: ^2.4.7
  build_runner: 2.4.11
  auto_route_generator: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
    - .env.staging
    - assets/img/
    - assets/lottie/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  ide: "idea"
  flavors:
    dev:
      app:
        name: "Base Dev"

      android:
        applicationId: "com.base.data.development"
      ios:
        bundleId: "com.base.data.development"
    staging:
      app:
        name: "Base Staging"

      android:
        applicationId: "com.base.data.staging"
      ios:
        bundleId: "com.base.data.staging"
    prod:
      app:
        name: "Base"

      android:
        applicationId: "com.base.data"
      ios:
        bundleId: "com.base.data"